#!/usr/bin/env python3.6
#
# http://adventofcode.com/2016/day/2

import pytest

class Keypad:
    def __init__(self, keys, start_key):
        self.keys = keys
        self.position = self.find_key(start_key)

    def find_key(self, key):
        for row_num, row in enumerate(self.keys):
            try:
                col_num = row.index(key)
            except ValueError:
                continue
            else:
                return (col_num, row_num)

    def current_key(self):
        return self.keys[self.position[1]][self.position[0]]

    def move(self, direction):
        deltas = {
            'U': (0, -1),
            'D': (0, 1),
            'L': (-1, 0),
            'R': (1, 0),
        }
        delta = deltas[direction]
        new_pos0 = self.position[0] + delta[0]
        new_pos1 = self.position[1] + delta[1]
        new_pos0_ok = 0 <= new_pos0 < len(self.keys[0])
        new_pos1_ok = 0 <= new_pos1 < len(self.keys)
        if new_pos0_ok and new_pos1_ok and self.keys[new_pos1][new_pos0] != " ":
            self.position = (new_pos0, new_pos1)

    def moves(self, directions):
        for direction in directions:
            if direction.isspace():
                continue
            self.move(direction)


class Keypad1thru9(Keypad):
    KEYS = [
        "123",
        "456",
        "789",
    ]

    def __init__(self):
        super().__init__(self.KEYS, "5")


def test_keypad_construction():
    kp = Keypad1thru9()
    assert kp.current_key() == "5"

SAMPLE_MOVES = """
    ULL
    RRDDD
    LURDL
    UUUUD
    """

def test_keypad_movement():
    kp = Keypad1thru9()
    kp.moves(SAMPLE_MOVES)
    assert kp.current_key() == "5"
    kp.moves("RD")
    assert kp.current_key() == "9"

def keypad_code_keys(keypad, directions):
    for line in directions.splitlines():
        if not line.split():
            continue
        keypad.moves(line)
        yield keypad.current_key()

def keypad_code(keypad, directions):
    return "".join(keypad_code_keys(keypad, directions))

def test_keypad_code():
    assert keypad_code(Keypad1thru9(), SAMPLE_MOVES) == "1985"

the_document_you_found_at_the_front_desk = """
LDUDDRUDRRURRRRDRUUDULDLULRRLLLUDDULRDLDDLRULLDDLRUURRLDUDDDDLUULUUDDDDLLLLLULLRURDRLRLRLLURDLLDDUULUUUUDLULLRLUUDDLRDRRURRLURRLLLRRDLRUDURRLRRRLULRDLUDRDRLUDDUUULDDDDDURLDULLRDDRRUDDDDRRURRULUDDLLRRDRURDLLLLLUUUDLULURLULLDRLRRDDLUDURUDRLRURURLRRDDLDUULURULRRLLLDRURDULRDUURRRLDLDUDDRLURRDRDRRLDLRRRLRURDRLDRUDLURRUURDLDRULULURRLDLLLUURRULUDDDRLDDUDDDRRLRDUDRUUDDULRDDULDDURULUDLUDRUDDDLRRRRRDLULDRLRRRRUULDUUDRRLURDLLUUDUDDDLUUURDRUULRURULRLLDDLLUDLURRLDRLDDDLULULLURLULRDLDRDDDLRDUDUURUUULDLLRDRUDRDURUUDDLRRRRLLLUULURRURLLDDLDDD
DRURURLLUURRRULURRLRULLLURDULRLRRRLRUURRLRRURRRRUURRRLUDRDUDLUUDULURRLDLULURRLDURLUUDLDUDRUURDDRDLLLDDRDDLUUDRDUDDRRDLDUDRLDDDRLLDDLUDRULRLLURLDLURRDRUDUDLDLULLLRDLLRRDULLDRURRDLDRURDURDULUUURURDLUDRRURLRRLDULRRDURRDRDDULLDRRRLDRRURRRRUURDRLLLRRULLUDUDRRDDRURLULLUUDDRLDRRDUDLULUUDRDDDDLRLRULRLRLLDLLRRDDLDRDURRULLRLRRLULRULDDDRDRULDRUUDURDLLRDRURDRLRDDUDLLRUDLURURRULLUDRDRDURLLLDDDRDRURRDDRLRRRDLLDDLDURUULURULRLULRLLURLUDULDRRDDLRDLRRLRLLULLDDDRDRU
URUUDUDRDDRDRRRDLLUDRUDRUUUURDRRDUDUULDUDLLUDRRUDLLRDLLULULDRRDDULDRLDLDDULLDDRDDDLRLLDLLRDUUDUURLUDURDRRRRLRRLDRRUULLDLDLRDURULRURULRRDRRDDUUURDURLLDDUUDLRLDURULURRRDRRUUUDRDDLRLRRLLULUDDRRLRRRRLRDRUDDUULULRRURUURURRLRUDLRRUUURUULLULULRRDDULDRRLLLDLUDRRRLLRDLLRLDUDDRRULULUDLURLDRDRRLULLRRDRDLUURLDDURRLDRLURULDLDRDLURRDRLUUDRUULLDRDURLLDLRUDDULLLLDLDDDLURDDUDUDDRLRDDUDDURURLULLRLUDRDDUDDLDRUURLDLUUURDUULRULLDDDURULDDLLD
LRRLLRURUURRDLURRULDDDLURDUURLLDLRRRRULUUDDLULLDLLRDLUDUULLUDRLLDRULDDURURDUUULRUDRLLRDDDURLRDRRURDDRUDDRRULULLLDLRLULLDLLDRLLLUDLRURLDULRDDRDLDRRDLUUDDLURDLURLUDLRDLDUURLRRUULDLURULUURULLURLDDURRURDRLUULLRRLLLDDDURLURUURLLLLDLLLUDLDLRDULUULRRLUUUUDLURRURRULULULRURDDRRRRDRUDRURDUDDDDUDLURURRDRRDRUDRLDLDDDLURRRURRUDLDURDRLDLDLDDUDURLUDUUDRULLRLLUUDDUURRRUDURDRRUURLUDRRUDLUDDRUUDLULDLLDLRUUDUULLDULRRLDRUDRRDRLUUDDRUDDLLULRLULLDLDUULLDRUUDDUDLLLLDLDDLDLURLDLRUUDDUULLUDUUDRUDLRDDRDLDRUUDUDLLDUURRRLLLLRLLRLLRLUUDULLRLURDLLRUUDRULLULRDRDRRULRDLUDDURRRRURLLRDRLLDRUUULDUDDLRDRD
DDLRRULRDURDURULLLLRLDDRDDRLLURLRDLULUDURRLUDLDUDRDULDDULURDRURLLDRRLDURRLUULLRUUDUUDLDDLRUUDRRDDRLURDRUDRRRDRUUDDRLLUURLURUDLLRRDRDLUUDLUDURUUDDUULUURLUDLLDDULLUURDDRDLLDRLLDDDRRDLDULLURRLDLRRRLRRURUUDRLURURUULDURUDRRLUDUDLRUDDUDDRLLLULUDULRURDRLUURRRRDLLRDRURRRUURULRUDULDULULUULULLURDUDUDRLDULDRDDULRULDLURLRLDDDDDDULDRURRRRDLLRUDDRDDLUUDUDDRLLRLDLUDRUDULDDDRLLLLURURLDLUUULRRRUDLLULUUULLDLRLDLLRLRDLDULLRLUDDDRDRDDLULUUR
"""

print(f"Puzzle 1: the bathroom code is {keypad_code(Keypad1thru9(), the_document_you_found_at_the_front_desk)}")


class KeypadDiamond(Keypad):
    KEYS = [
        "  1  ",
        " 234 ",
        "56789",
        " ABC ",
        "  D  ",
    ]

    def __init__(self):
        super().__init__(self.KEYS, "5")

def test_diamond_code():
    assert keypad_code(KeypadDiamond(), SAMPLE_MOVES) == "5DB3"

print(f"Puzzle 2: the bathroom code is {keypad_code(KeypadDiamond(), the_document_you_found_at_the_front_desk)}")
